### ISSUE TITLE
Need detail instructions for compilation

### ISSUE THREAD

**Issue by pspishnik** [OpenMW/android-port#25] opened 2016-07-07 14:39 UTC
So many words,i dont understand so much,need more details

**Comment by street-grease-coder** [comment] 2016-08-01 12:32
I agree, it could be much clearer so others may join the development!

**Comment by OwnageIsMagic** [comment] 2016-08-01 19:51
For me it looks pretty straight forward:

1. Download all deps.
2. Compile all dependencies as simple as `ndk-build APP_PLATFORM=android-14 APP_ABI=armeabi-v7a` unless stated otherwise.
3. Copy all deps to `app/src/main/jniLibs/armeabi-v7a`.
4. Compile APK.

But it would be more user friendly if @sandstranger uploaded all prebuilt deps to https://github.com/OpenMW/android-port/downloads

**Comment by psi29a** [comment] 2016-08-02 08:10
The github downloads tab is deprecated. So we'll need another way to host prebuilt deps.

**Comment by OwnageIsMagic** [comment] 2016-08-02 08:56
Maybe releases section?

**Comment by pavlukivan** [comment] 2016-08-14 04:48
There was all prebuilt deps archive somwhere on google drive, but now it's private

**Comment by pspishnik** [comment] 2016-08-14 22:37
em....so....how we can get it?maybe to help with port,and em...."play")))

**Comment by sandstranger** [comment] 2016-09-07 09:15
this dependencies have been compiled with unpacking  dxt textures , 
therefore were removed

**Comment by pspishnik** [comment] 2016-12-20 16:53
это значит, что в ближайшее время вообще никакого варианта запуска OpenMW не будет на андроиде?просто написал бы хоть немного по понятнее инструкцию...я как чайник почти не шарю в программировании....

**Comment by pspishnik** [comment] 2016-12-20 16:53
ну или выложил бы хотя бы готовые библиотеки с вшитыми зависимостями,которые надо уже закинуть в архив, дать расширение .apk и запускать

**Comment by pspishnik** [comment] 2016-12-20 16:56
и вот конкретно на моей памяти, tegra k1 умеет dxt текстуры открывать и работать с opengl 3.0

**Comment by pavlukivan** [comment] 2016-12-20 16:57
@pspishnik, советую перевести, тут мало людей дарят в русском. А вообще "закинуть в архив, дать расширение apk и запустить" это абсурд

**Comment by pspishnik** [comment] 2016-12-20 17:06
а ты?ты смог скомпилить хотя бы?

**Comment by pspishnik** [comment] 2016-12-20 17:07
@pavlukivan а ты?смог хоть скомпилировать это все в единое апк?

**Comment by pavlukivan** [comment] 2016-12-20 17:37
Я и не пытался

**Comment by Phatcat** [comment] 2016-12-20 22:49
I wanted to get into development for this project, I have been developing a slight bit on the android port of dolphin emulator in the past, and have been helping develop the cmangos project quite a bit this year (wow emulation)

I really have not much of a clue how to set up the build environment, though, there is no step by step guide to make sure you set up all dependancies and get everything build right, everything is scattered, fragmented and lacking in the documention department.

Also I am not sure why so many different repos? is this needed for allowing implementation in retro-arch and the like?

**Comment by psi29a** [comment] 2016-12-21 08:44
@Phatcat Please have at it.

I think we is needed here is way to automate dependency building, when we have to but also offer pre-built libs. We do this already for OSX to help speed up Travis-CI.

I'm wondering if we can't have Travis-CI setup a build environment to use crystax-sdk (sp?). 

With a guide so that others can build.

Just to be clear, OpenMW has no problem with hosting builds of OpenMW for Android as apk files. We also have no problems with showing videos of it running with the Template or Example-Suite. That is all good! So while @sandstranger has been working behind the scenes, it would be great if someone could be the public face of this side of the OpenMW project for Android. :)

**Comment by Phatcat** [comment] 2016-12-21 09:00
Wouldn't a project branching out to platforms such as android (going beyond the standard linux and windows platforms) benefit more from buldbot? http://buildbot.net/

I know dolphin uses buildbot, but cmangos uses AppVeyor and Travis-CI

**Comment by pspishnik** [comment] 2016-12-21 10:43
@psi29a you're so funny, nobody can be "face" of openmw-android, cuz bethesda have anti-port(:D) politcs, and because of that sandstrander does'not develop complete work...and also we dont need complete apk,everyone just want's much more easy way yo compilate his work...

**Comment by Phatcat** [comment] 2016-12-21 10:47
Bethesda has no claim, right, or control over this open source project ;)

**Comment by psi29a** [comment] 2016-12-21 10:48
@pspishnik Actually, you're wrong. I'm the one that negotiated with Bethesda and made our deal that we don't publish any videos showing Morrowind running on Android.

Feel free to read my emails: https://wiki.openmw.org/index.php?title=Bethesda_Emails

We can develop for Android and we can show videos of it running the Template and Example-Suite because they do not have any Bethesda IP in them.

I've worked with Sandstranger for years now, I know how he feels about the project and have supported through tough times. If someone wants to take up the charge of being the lead developer of the Android port, they will do so with OpenMW's blessing.

**Comment by Phatcat** [comment] 2016-12-21 10:56
Okay, so they have a bit of control... Which doesn't make much sense since you'd not be violating the fair use clause by showing such videos, though, you are allowed to show parts of someone elses IP for different purposes, showcasing emulation is one of them.

If dmca-happy nintendo could, they would've shut down videos showcasing dolphin on both android and pc, but they can't. Dolphin even releases their own videos... How would bethesda be able to shut down your videos or even come after you guys? none of these repos contain any of their copyrighted material, do they?

**Comment by psi29a** [comment] 2016-12-21 11:01
No, none of the repos have any Bethesda IP in them.

We made an agreement with them that 'we' (OpenMW) wouldn't show any videos of their IP running on Android. This was done in good faith to avoid getting all the lawyers in the room and wasting everyone's time and money. Let alone the headache of having to deal with cease & decease letters.

We would rather remain on good terms with Bethesda, which we are. :)

This does not mean that someone else makes videos of OpenMW running Morrowind on Android on their website/blog/whatever. It is outside the scope of the deal.

**Comment by sandstranger** [comment] 2016-12-22 18:55
You can not simple run this engine on Android , A made ton of hacks on my phone for running it on my phone

**Comment by psi29a** [comment] 2016-12-23 06:53
2nd: The patent on S3 Texture Compression expires on October 2, 2017. Here is a nice countdown website: http://www.patentcountdown.org/

Provided no one attempts to renew it, we can introduce s3tc decompressor into OpenMW itself.

**Comment by Phatcat** [comment] 2016-12-26 14:55
Just wanna hammer this home to sandstranger;

https://en.wikipedia.org/wiki/Reverse_engineering#Legality
> Reverse engineering is a process of examination only: the software system under consideration is not modified (which would make it re-engineering). Software anti-tamper technology like obfuscation is used to deter both reverse engineering and re-engineering of proprietary software and software-powered systems. In practice, two main types of reverse engineering emerge. In the first case, source code is already available for the software, but higher-level aspects of the program, perhaps poorly documented or documented but no longer valid, are discovered. **In the second case, there is no source code available for the software, and any efforts towards discovering one possible source code for the software are regarded as reverse engineering. This second usage of the term is the one most people are familiar with. Reverse engineering of software can make use of the clean room design technique to avoid copyright infringement.**

->

https://en.wikipedia.org/wiki/Clean_room_design
> The term implies that the design team works in an environment that is "clean" or demonstrably uncontaminated by any knowledge of the proprietary techniques used by the competitor.
(...)
Clean room design is usually employed as best practice, but not strictly required by law. In NEC Corp. v Intel Corp. (1990), NEC sought declaratory judgment against Intel's charges that NEC's engineers simply copied the microcode of the 8086 processor in their NEC V20 clone. **A US judge ruled that while the early, internal revisions of NEC's microcode were indeed a copyright violation, the later one, which actually went into NEC's product, although derived from the former, were sufficiently different that they could be considered free of copyright violations.** 

Even if openmw couldn't claim clean room, then there's still no violation if none of the copyrighted code is directly used;

https://en.wikipedia.org/wiki/Emulator#Legal_issues
> As computers and global computer networks continued to advance and emulator developers grew more skilled in their work, the length of time between the commercial release of a console and its successful emulation began to shrink. Fifth generation consoles such as Nintendo 64, PlayStation and sixth generation handhelds, such as the Game Boy Advance, saw significant progress toward emulation during their production. This led to an effort by console manufacturers to stop unofficial emulation, but consistent failures such as Sega v. Accolade 977 F.2d 1510 (9th Cir. 1992), Sony Computer Entertainment, Inc. v. Connectix Corporation 203 F.3d 596 (2000), and Sony Computer Entertainment America v. Bleem 214 F.3d 1022 (2000),[28] have had the opposite effect. **According to all legal precedents, emulation is legal within the United States.**

But console emulation can't be directly compared to software emulation you say? Well no, I agree, but server emulation can be;

https://en.wikipedia.org/wiki/Private_server
> Private server can specifically mean a server emulator, a reimplementation of online game server such as MMORPG genres like World of Warcraft or The Exiled Realm of Arborea. Private machines can be used in various experimental projects such as games under development or various innovative startups.[3]

->

https://en.wikipedia.org/wiki/Server_emulator#Legality
> Emulating the server of the proprietary commercial game often violates EULA as many commercial MMORPGs require the user to sign a clause not to create or use server emulators. It may also violate DMCA and has all issues, typical for reverse engineering of any kind. The server may try to avoid violations by serving from the country where some intellectual property laws apply differently or not at all.

> **Another issue is a possible infringement of the game creator's copyright. If the complete emulator is a work of its own, copyright violation is not as obvious as EULA violation (see Lotus v. Borland case).** However sometimes the original server software leaks out of the company that created the game, for example AEGIS (Ragnarok Online). Use or distribution of leaked code is widely held to be copyright infringement. **There are cases where a game creator has effectively shut down private game servers by threatening lawsuits due to intellectual property violations, such as offering a modified client (see information on NEXON v OdinMS) for download or offering downloads of modified files from the original game package.**

This is why I made a point to ask if your repos contained any copyrighted material, or any assets from the game at all, if not, then there's nothing to claim copyright of, is there?

->

https://en.wikipedia.org/wiki/Lotus_Development_Corp._v._Borland_International,_Inc.
> The Lotus decision establishes a distinction in copyright law between the interface of a software product and its implementation. The implementation is subject to copyright. The public interface may also be subject to copyright to the extent that it contains expression (for example, the appearance of an icon). **However, the set of available operations and the mechanics of how they are activated are not copyrightable.[7]:211-215 This standard allows software developers to create competing versions of copyrighted software products without infringing the copyright. See software clone for infringement and compliance cases.**

**Comment by psi29a** [comment] 2016-12-26 14:58
@Phatcat as I said, we've already been over this. Sandstranger just doesn't want to be in the spotlight. If there is anything 'official' happening with the Android OpenMW port, his (I'm assuming him) doesn't want his name on it. We should honor that request and let him develop in peace. :)

**Comment by Phatcat** [comment] 2016-12-26 16:49
Sure, my point was 100% in his defense, all respect to this project and his work and 0% respect to bethesda for strong-arming this project, specifically it's android port...
I'll try to get it build and running on my end, I hope that my samsung s7 or nvidia shield android tv will be enough.. sandstranger did not make it sound like an easy task, though..

**Comment by sandstranger** [comment] 2016-12-27 10:37
@Phatcat ,samsung s7 have got mali videocard , mali drivers awful , ecpecially for this engine , so this engine will crash very often in graphics drivers .

**Comment by street-grease-coder** [comment] 2016-12-28 10:15
@sandstranger: I read your interesting response about releasing prebuilt libs etc, thank you. Obviously it is extremely frustrating to see fragments of the real running project on a opensource sharing platform like github because fear of legal ramifications for individuals. In my opinion this shouldn't be continued as open source because of Bethesda's strong-arming. Shame on Bethesda.

**Comment by psi29a** [comment] 2016-12-28 16:52
@street-grease-coder what are you talking about? How is Bethesda strong arming anything? Don't shame a company for something they haven't done. Bethesda isn't blocking  or otherwise hindering development of OpenMW on Android, so what exactly is your problem?

**Comment by Phatcat** [comment] 2016-12-28 19:02
Yeah, those were my words. They may not be hindering any development directly, but by not allowing videos and posts to be made about the progress of the android port in terms of actual emulation of the morrowwind game, they are kind of strong-arming in that sense, for lack of a better term, and it very much does seem to affect sandstranger. Me personally am only shaming them for doing that. Also in street-grease-coder's defense he is right that the android port is, if nothing else, obscured, because of fear of legal ramifications.
Also that is just my take on it from reading the e-mails as well as this conversation on this issue

**Comment by psi29a** [comment] 2016-12-28 21:46
The only reason that OpenMW's Android port is in the state that it is in is because Sandstranger is the only one working on it. Had anyone else wanted to work on it, perhaps it would be in a better state than it is now. This is not Bethesda's fault.

The facts are:
1) If anyone wants to work on the OpenMW Android port, they are protected under law in doing so.
2) Morrowind is Bethesda's "Intellectual Property" and they are well within their rights to defend and enforce this. "Fair use" doctrine is a US legal concept that isn't universally accepted the world over. Bethesda may force videos down in non-US jurisdictions since it is their IP being displayed. They have so far not done this however.
3) OpenMW and Bethesda agreed that OpenMW would not show videos of Morrowind on running on Android. Videos of OpenMW on the other hand are just fine and if we had them, we would display them proudly.

I do not see how this hinders or otherwise obscures development. If someone wants to step up to be a real OpenMW developer to take responsibility for the port, then they will have the full support of the OpenMW team and yes, we will post about it on the OpenMW website and forums.

If you want to help, great. If you want to bitch about Bethesda, please do it somewhere else as this is not the place for it.

**Comment by Phatcat** [comment] 2016-12-28 23:44
I'm sorry if I made it out to seem like I was having a go at bethesda, I can see how it would come off like that. I wasn't trying to, they are very far from the worst company out there in terms of being 'protective' of their ip. Even though I do not entirely agree, I am gonna respect the first part of point 3 and leave it be.

Also I do want to help work on it, if I am able to that is.

**Comment by psi29a** [comment] 2016-12-28 23:54
Great, how can I help you get started? :)

If you need to talk with Sandstranger, you can talk with them via PM in the forums.

**Comment by Phatcat** [comment] 2016-12-29 00:21
Well, for starters it would be nice to know if it's possible to even compile the android port on windows or if it needs to be done on linux? 

There is made a note of a architecture that is supported, but it doesn't mention which architectures are supported, so that you can be sure that your architecture is supported, should you not have the one that is mentioned. as a bonus it would also be nice to note how to generally find that info on a device (even though that may be asking for something out of scope for this guide)

For building OSG it links to two guides, but doesn't state directly, if, both are needed, or how to know which one to follow for your phone, or if you should follow a whole other one should your architecture not match the one mentioned above.

There is nothing to explain the interconectivity of all these dependencies, according to the guide they seem to be build just for the sake of building them more or less.

Generally the instructions for setting up the build environment is nowhere near as detailed or thorough as https://wiki.openmw.org/index.php?title=Development_Environment_Setup

Not.. that it has to be.. I just like instructions that are direct and exhaustive (as the wiki)

**Comment by Phatcat** [comment] 2016-12-29 00:31
Also several of the things mentioned here by sandstranger don't seem to appear in the guide on the readme either, such that he has hacked his phone and runs a custom android os, that you need to run custom drivers for most phones (since most phones are on mali), that you need to run gl4es, that you need to modify some of the dependencies for openmw, and there's probably some more I missed as well..

**Comment by Phatcat** [comment] 2016-12-29 00:39
Personally, I would also love to see it seperated into two sections (with any number of subsections);

One for everything that needs to be set up on your workstation to be able to build the openmw android apk.

and one for everything that needs to be set up and prepared on the device to be able to run the openmw apk.

**Comment by Phatcat** [comment] 2016-12-29 01:12
Also since this project seems to use both boost and cmake could it perhaps be of gain to take use of a project such as this; https://github.com/Orphis/boost-cmake ?

**Comment by sandstranger** [comment] 2016-12-29 07:32
I am using my custom android build , because My phone's manufacturer  uses graphics drivers frrom android 5 even  on android 7.1.1

**Comment by psi29a** [comment] 2016-12-31 09:27
I have no idea about Windows, I haven't used it (and VS) in a really long time and don't really miss it. However I assume that Crystax NDK and the rest are cross platform. I would suggest giving it a go yourself and documenting the journey so that others can follow in your footsteps.

You can always fire up a virtual machine with a Linux guest, that would be less painful then dealing with dual-booting.

From what I remember, ARMv6 was buggy regardless of Ogre3D or OSG. ARMv7 (32-bit) seemed to work as far as I remember. All of my builds for ARM are for ARM64 and ARMHF for use with RPi2. They all work so long as your device supports OpenGL (libGL) 2.0. If your device only supports OpenGLES (v1 or v2) then you're going to have to use the GLShim to translate some calls.

@sandstranger do you have any more information on the above?

As for the documentation as it stands now, feel free to have your way with it and send a PR. SS and I can review it and help get it into shape. 

I would like to see something that can be reproducible, that way we can use buildbot or something to create automated builds.

If you think you can make use of boost-cmake, give it a try and see how it works for you.

**Comment by sandstranger** [comment] 2016-12-31 18:13
openmw for android can be compiled for any architecture supported by android ndk , 
I also have no idea about Windows , android ndk supported  Windows ,
so in theory it is possible to build it on Windows

**Comment by psi29a** [comment] 2017-01-01 09:57
OpenMW will get a Vulkan tenderer when OSG gets an Vulkan render.

**Comment by sandstranger** [comment] 2017-01-01 18:29
vulkan render supported  only from android 7

**Comment by sandstranger** [comment] 2017-01-01 18:49
Also this two PR needed to be merge into main repo , without it , engine will not work on Android
https://github.com/OpenMW/openmw/pull/1090
https://github.com/OpenMW/openmw/pull/1093

**Comment by Allofich** [comment] 2017-01-03 07:05
> Also this two PR s needed to be merged into main repo , without it , engine will not work on Android

There doesn't seem to be any movement toward merging those two PRs. They are linked to this thread now, which is how I came here, but maybe you should explain in the PRs that they are necessary for Android to work. The OpenMW developers might not be trying to run OpenMW on Android and might be unable to test or be unsure of your changes.

**Comment by sandstranger** [comment] 2017-01-06 00:35
Any news about building ? If it so hard to build, I can build armv7 dependencies and sent it to openmw developers . But please , do not say ,that I build it

**Comment by psi29a** [comment] 2017-01-06 12:40
@sandstranger that would be a good idea if you could gather up all the dependencies. We (OpenMW) can host those deps and provide a link for in the readme. That would make things easier for people wanting to build their own OpenMW.

**Comment by pspishnik** [comment] 2017-01-12 21:51
> We (OpenMW) can host those deps and provide a link for in the readme. That would make things easier for people wanting to build their own OpenMW.

> 

i dont think this is BEST idea...but for nothing its good...but remember bethesda is dont sleep...they can close this repo...and much people went away from OpenMW on android....

p.s. still waiting stable version to start,my Nvidia shield tablet wants openmw XDDDDD

**Comment by psi29a** [comment] 2017-01-12 23:07
@pspishnik you have absolutely no idea what you're talking about do you? If you do not stop posting FUD, I'll have to start deleting your posts. Consider it a warning.

**Comment by sandstranger** [comment] 2017-01-20 07:43
how to build osg ?
with gles1 or opengl rendering  ?

**Comment by psi29a** [comment] 2017-01-20 08:16
use opengl,  gles1 won't work... I ended up getting black textures and lots of warnings.  OpenMW just doesn't support gles1.

**Comment by sandstranger** [comment] 2017-02-14 17:36
just small update . openmw also works with gogle ndk v13 .
I build it for am64 just now

**Comment by sandstranger** [comment] 2017-02-15 05:14
Just small update . openmw also workes on google ndk r13b .

**Comment by psi29a** [comment] 2017-02-15 07:01
That's great news. :)  Do you need any help from me? Can we host your deps? If we do that, we can make travis-ci or other CI builds of android.

**Comment by xyzz** [comment] 2018-01-16 13:36
With the latest updates it should be trivial to build on Linux, other platforms (OSX/Windows) maybe coming eventually? Try following the README and open an issue if the build fails for you.

**Closed by xyzz** 2018-01-16 13:36 UTC
